<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="helloworld_tests.HelloWorldTest-20160113192311" tests="1" time="0.002">
	<testcase classname="helloworld_tests.HelloWorldTest" name="test_should_issue_hello_world_message" time="0.002">
		<failure message="
Wanted but not invoked: write('Hellooo world of Python\n')" type="VerificationError">
<![CDATA[Traceback (most recent call last):
  File "c:\Users\ynaveenkumar\Py_dev_virt_cont\py_buildtool\helloworld\src/unittest/python\helloworld_tests.py", line 12, in test_should_issue_hello_world_message
    verify(out).write("Hellooo world of Python\n")
  File "c:\users\ynaveenkumar\py_dev_virt_cont\py_buildtool\lib\site-packages\mockito\invocation.py", line 111, in __call__
    verification.verify(self, len(matched_invocations))
  File "c:\users\ynaveenkumar\py_dev_virt_cont\py_buildtool\lib\site-packages\mockito\verification.py", line 63, in verify
    raise VerificationError("\nWanted but not invoked: %s" % (invocation))
VerificationError: 
Wanted but not invoked: write('Hellooo world of Python\n')
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
